name: Deploy BOT
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          timeout: 40m
          script: |
            cd ~/chasse-aux-sorcieres/bot
            git pull origin main
            cd ..

            # 1. On build d'abord (sécurisé par la limite de RAM dans le Dockerfile)
            docker compose build bot
            # 2. On applique le changement instantanément
            docker compose up -d bot
            # 3. Nettoyage
            docker image prune -f
